workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Create assets directories
        script: |
          mkdir -p assets/images
          mkdir -p assets/icons
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos
      - name: Clean and build
        script: |
          flutter clean
          flutter pub get
      - name: Build release APK
        script: |
          flutter build apk --release --verbose
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - thiagowifi1234@gmail.com
        notify:
          success: true
          failure: true